# Numpy
Numpy  - Numerical Python

Adv of numpy
- Allows several mathematical operations
- Speed

In [1]:
import numpy as np

List vs Numpy

In [2]:
from time import process_time

In [6]:
b=  np.array([(1,2,3,4),(6,7,8,9)])
print(b)
b.shape

[[1 2 3 4]
 [6 7 8 9]]


(2, 4)

In [11]:
# INitial placeholders
c = np.zeros((3,3))
# print(c)
#identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
c = np.random.randint(0,5,(3,3))
print(c)

[[1 3 2]
 [0 3 4]
 [3 2 4]]


In [23]:
# evenly spaced
d = np.linspace(5,15,2)
print(d)
e = np.linspace(10,30,5)
print(e)

[ 5. 15.]
[10. 15. 20. 25. 30.]


In [33]:
arr = np.random.randint(0,5,(2,3))
print(arr)

arr.shape

print('Changed')
arr = arr.T
print(arr)
arr.shape

[[3 0 2]
 [0 1 0]]
Changed
[[3 0]
 [0 1]
 [2 0]]


(3, 2)

In [35]:
b = arr.reshape(2,3)
print(b)

[[3 0 0]
 [1 2 0]]
